// Sprite system: pink-chroma-keyed animated billboards driven by shaders.
// Sheets are generated by tools/gen-sprites.js (uniform grid, centered sprites)
// and can be replaced 1:1 with Nano Banana Pro output as long as the layout
// (1 row x N frames, 64x64 cells, bright-pink key background) is kept.
import * as THREE from 'three';

const CELL = 64; // spritesheet cell size (matches tools/gen-sprites.js)

// Manifest is loaded at runtime (assets live in public/, served at /assets).
let manifestPromise = null;
function getManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch('assets/sprites/manifest.json').then((r) => {
      if (!r.ok) throw new Error(`manifest fetch failed: ${r.status}`);
      return r.json();
    });
  }
  return manifestPromise;
}

const VERT = /* glsl */ `
  uniform vec3 uRight;
  uniform vec3 uUp;
  uniform vec2 uSize;
  uniform vec3 uWorldPos;
  varying vec2 vUv;
  void main() {
    vUv = uv;
    vec3 worldPos = uWorldPos + position.x * uRight * uSize.x + position.y * uUp * uSize.y;
    gl_Position = projectionMatrix * viewMatrix * vec4(worldPos, 1.0);
  }
`;

const FRAG = /* glsl */ `
  uniform sampler2D uMap;
  uniform vec2 uOffset;
  uniform vec2 uScale;
  uniform vec3 uKeyColor;
  uniform float uKeySoft;
  uniform vec3 uTint;
  uniform float uAlpha;
  varying vec2 vUv;
  void main() {
    vec2 uv = vUv * uScale + uOffset;
    vec4 c = texture2D(uMap, uv);
    float d = distance(c.rgb, uKeyColor);
    float a = smoothstep(uKeySoft, uKeySoft * 3.0, d) * c.a * uAlpha;
    gl_FragColor = vec4(c.rgb * uTint, a);
  }
`;

const KEY_PINK = new THREE.Color(1, 0, 1);
const NEAREST = { magFilter: THREE.NearestFilter, minFilter: THREE.NearestFilter, generateMipmaps: false };

/** An animated sprite: a camera-facing plane with per-frame sheet animation. */
export class AnimatedSprite {
  /**
   * @param {string} actor  manifest actor name, e.g. 'imp', 'torch'
   * @param {number} height world height of the sprite
   */
  constructor(actor, height) {
    this.actor = actor;
    this.height = height;
    this.sheets = {};      // anim name -> { texture, frames }
    this.material = new THREE.ShaderMaterial({
      vertexShader: VERT,
      fragmentShader: FRAG,
      uniforms: {
        uMap: { value: null },
        uOffset: { value: new THREE.Vector2(0, 0) },
        uScale: { value: new THREE.Vector2(1, 1) },
        uRight: { value: new THREE.Vector3(1, 0, 0) },
        uUp: { value: new THREE.Vector3(0, 1, 0) },
        uSize: { value: new THREE.Vector2(1, 1) },
        uWorldPos: { value: new THREE.Vector3() },
        uKeyColor: { value: KEY_PINK.clone() },
        uKeySoft: { value: 0.08 },
        uTint: { value: new THREE.Color(1, 1, 1) },
        uAlpha: { value: 1 },
      },
      transparent: true,
      depthWrite: false,
    });
    this.mesh = new THREE.Mesh(new THREE.PlaneGeometry(1, 1), this.material);
    this.mesh.visible = false;
    this.frame = 0;
    this.anim = null;
    this.fps = 8;
    this.loop = true;
    this.timer = 0;
    this.onComplete = null;
    this.material.uniforms.uSize.value.set(this.height, this.height);
  }

  /** Preload one animation sheet (returns a promise). */
  async load(animName) {
    if (this.sheets[animName]) return this.sheets[animName];
    const manifest = await getManifest();
    const file = manifest.actors?.[this.actor]?.anims?.[animName];
    if (!file) {
      console.warn(`[sprites] no animation '${animName}' for '${this.actor}'`);
      return null;
    }
    return new Promise((resolve) => {
      new THREE.TextureLoader().load(`assets/sprites/${file}`, (tex) => {
        tex.magFilter = NEAREST.magFilter;
        tex.minFilter = NEAREST.minFilter;
        tex.generateMipmaps = false;
        tex.colorSpace = THREE.SRGBColorSpace;
        const info = manifest.animations[file];
        const sheet = { texture: tex, frames: info.frames, cols: info.cols };
        this.sheets[animName] = sheet;
        if (this.anim === animName) this._applySheet(sheet);
        resolve(sheet);
      });
    });
  }

  _applySheet(sheet) {
    this.material.uniforms.uMap.value = sheet.texture;
    this.material.uniforms.uScale.value.set(1 / sheet.cols, 1);
    this.material.needsUpdate = true;
  }

  setAnimation(name, { fps = 8, loop = true, onComplete = null } = {}) {
    if (this.anim === name && this.sheets[name]) return;
    this.anim = name;
    this.fps = fps;
    this.loop = loop;
    this.onComplete = onComplete;
    this.frame = 0;
    this.timer = 0;
    if (this.sheets[name]) {
      this._applySheet(this.sheets[name]);
    } else {
      this.load(name);
    }
  }

  playOnce(name, onComplete, fps = 10) {
    this.setAnimation(name, { fps, loop: false, onComplete });
  }

  update(dt, camera) {
    const sheet = this.sheets[this.anim];
    if (!sheet) return;
    if (!this.mesh.visible) this.mesh.visible = true;
    const { frames, cols } = sheet;
    this.timer += dt;
    const per = 1 / this.fps;
    while (this.timer >= per) {
      this.timer -= per;
      this.frame++;
      if (this.frame >= frames) {
        if (this.loop) {
          this.frame = 0;
        } else {
          this.frame = frames - 1;
          if (this.onComplete) {
            const cb = this.onComplete;
            this.onComplete = null;
            cb();
          }
        }
      }
    }
    const u = this.material.uniforms;
    u.uOffset.value.set(this.frame / cols, 0);
    u.uWorldPos.value.copy(this.mesh.position);
    // billboard against camera
    const m = camera.matrixWorld.elements;
    u.uRight.value.set(m[0], m[1], m[2]);
    u.uUp.value.set(m[4], m[5], m[6]);
  }

  setTint(r, g, b) { this.material.uniforms.uTint.value.set(r, g, b); }
  setAlpha(a) { this.material.uniforms.uAlpha.value = a; }
  set size(h) { this.material.uniforms.uSize.value.set(h, h); }

  dispose() {
    this.mesh.geometry.dispose();
    this.material.dispose();
    for (const s of Object.values(this.sheets)) s.texture.dispose();
  }
}

/** Convenience: create an animated sprite in a scene, positioned at y=0 feet. */
export function spawnSprite(scene, actor, height, x, z) {
  const s = new AnimatedSprite(actor, height);
  s.mesh.position.set(x, height / 2, z);
  scene.add(s.mesh);
  return s;
}
